### ISSUE TITLE
cannot marshal string as a BSON doc

### ISSUE THREAD

**Issue by adesokanayo** [adesokanayo/webapp#2]
i have the above error a this point.  Even thought I get the message , but I don't  know what to do to be able to achieve the conversion.

`result := []User{}

```
err := s.All(&result)

if err != nil {
    log.Println("unable to show users")
    fmt.Print(err)
}`
```

![img0000](https://cloud.githubusercontent.com/assets/5377446/18814600/6ffe9cd8-8310-11e6-8d6c-a8c393db5e33.PNG)

**Comment by influx6** [comment]
This here seems to try to marshal not unmarshal. tag the point in code here

**Comment by adesokanayo** [comment]
I think I got  the way is. retrieving with my find should have come with a bson below.

```
err := c.Find(bson.M{}).All(&result)
```

Now it works, i can retrieve from mongodb. I will push a fresh commit now, It's also cleaner.
